name: Florvåg Skole FAU
markdown: kramdown
kramdown:
    smart_quotes: lsquo,rsquo,laquo,raquo
relative_permalinks: false
#permalink: /:categories/:year/:month/:day/
#permalink: pretty
#permalink: /:categories/:year/:title/
permalink: /:categories/:title/
future: false
